import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'
import Header from './components/header'
import { Provider } from 'react-redux'
import store from '../redux/store'
import Providers from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies db',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers store={store}>  

        <Header></Header>
        <main>
        {children}
        </main>
        </Providers>

        </body>
    </html>
  )
}
